import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Shop Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        <Navbar />
        <div className="container mx-auto px-25">
          <Toaster />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
